/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    {type: 'category',
      label:'VisionMaster使用',
      link:{type:'generated-index'},
      items:[
        {
          label: '掌握VM各模块使用',
          type: 'category',
          link: { type: 'generated-index' },
          items: [
            {
              type: 'autogenerated',
              dirName: 'vm-usage-tutorial/master-various-vm-modules',
            },
          ],
        },
        {
          label: '学会通信',
          type: 'category',
          link: { type: 'generated-index' },
          items: [
            {
              type: 'autogenerated',
              dirName: 'vm-usage-tutorial/association-communication',
            },
          ],
        },
        {
          label: '实战VM项目-无项目素材',
          type: 'category',
          link: { type: 'generated-index' },
          items: [
            {
              type: 'autogenerated',
              dirName: 'vm-usage-tutorial/practical-vm-project',
            },
          ],
        },
        
      ]
    },
    { type:'category',
      label:'二次开发',
      link:{type:'generated-index'},
      items:[
        {
          label: '环境配置',
          type: 'category',
          link: { type: 'generated-index' },
          items: [
            {
              type: 'autogenerated',
              dirName: 'secondary-development/environment-config',
            },
          ],
        },
        {
          label: '流程介绍',
          type: 'category',
          link: { type: 'generated-index' },
          items: [
            {
              type: 'autogenerated',
              dirName: 'secondary-development/process-introduction',
            },
          ],
        },
        {
          label: 'Group流程操作',
          type: 'category',
          link: { type: 'generated-index' },
          items: [
            {
              type: 'autogenerated',
              dirName: 'secondary-development/group',
            },
          ],
        },
        {
          label: '综合开发',
          type: 'category',
          link: { type: 'generated-index' },
          items: [
            {
              type: 'autogenerated',
              dirName: 'secondary-development/integrated-development',
            },
          ],
        },
      ]
    },
    
  ],
  
};

export default sidebars;
